In [1]:
# Import libraries
import pandas as pd
import pandas_profiling as pp
import matplotlib.pyplot as plt
import numpy as np
import sys
import matplotlib
import math
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error 
from sklearn.linear_model import RidgeCV, Ridge, LassoCV, Lasso
%matplotlib inline

In [2]:
df = pd.read_csv(r'C:\Users\grays\Desktop\summary_portfolio.csv', index_col = 'ID')
print(df)

#Create numpy arrays with  the features and the target.
X_train = df[['VATD_NA', 'VATD_PASSIVE','VATD_ALARM','DMA_mean','DMA_std','VAY_mean','VAY_std','AP_mean','AP_std']].to_numpy()
y_train = df['ln_LR'].to_numpy()

      VATD_NA  VATD_PASSIVE  VATD_ALARM   DMA_mean    DMA_std  VAY_mean  \
ID                                                                        
1    0.583000      0.321000    0.071000  46.163000  15.379823  6.925000   
2    0.610611      0.292292    0.079079  45.875876  15.812168  7.078078   
3    0.591592      0.316316    0.071071  46.519520  16.307214  7.133133   
4    0.591000      0.310000    0.082000  46.000000  15.641248  7.095000   
5    0.614228      0.299599    0.065130  46.131263  15.846993  7.065130   
..        ...           ...         ...        ...        ...       ...   
496  0.573721      0.317954    0.091274  45.816449  16.428114  6.881645   
497  0.599000      0.300000    0.079000  46.667000  15.441974  6.921000   
498  0.576000      0.324000    0.071000  46.144000  16.020609  6.920000   
499  0.589178      0.312625    0.068136  46.801603  15.845883  7.101202   
500  0.570571      0.343343    0.066066  46.125125  16.011186  6.978979   

      VAY_std     AP_mea

In [3]:
#Print the means and stds of the input features.
print('X_train = ', X_train)
print('mean(X_train) = ', X_train.mean(axis=0))
print('std(X_train) = ', X_train.std(axis=0))

X_train =  [[5.83000000e-01 3.21000000e-01 7.10000000e-02 ... 2.62721854e+00
  3.35174720e+02 1.91695616e+02]
 [6.10610611e-01 2.92292292e-01 7.90790791e-02 ... 2.54142235e+00
  3.34791311e+02 2.00948218e+02]
 [5.91591592e-01 3.16316316e-01 7.10710711e-02 ... 2.50236227e+00
  3.31441041e+02 2.25410729e+02]
 ...
 [5.76000000e-01 3.24000000e-01 7.10000000e-02 ... 2.66696695e+00
  3.38915100e+02 2.06702881e+02]
 [5.89178357e-01 3.12625251e-01 6.81362725e-02 ... 2.54444516e+00
  3.35518206e+02 2.19532722e+02]
 [5.70570571e-01 3.43343343e-01 6.60660661e-02 ... 2.56509610e+00
  3.44678188e+02 2.28825738e+02]]
mean(X_train) =  [5.84589960e-01 3.15274188e-01 7.54654716e-02 4.62132665e+01
 1.59554738e+01 7.02638288e+00 2.58356890e+00 3.36290613e+02
 2.06884042e+02]
std(X_train) =  [1.58864903e-02 1.40942274e-02 8.66884737e-03 5.04194157e-01
 3.19051019e-01 8.45302694e-02 5.27599241e-02 6.76279120e+00
 1.10409155e+01]


In [4]:
#Scale the input features such that the all have zero mean and unit standard deviation.
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

print('X_train_scaled = \n', X_train_scaled)
print('mean(X_train_scaled) = ', X_train_scaled.mean(axis=0))
print('std(X_train_scaled) = ', X_train_scaled.std(axis=0))

X_train_scaled = 
 [[-0.10008252  0.40625227 -0.51511711 ...  0.82732581 -0.16500482
  -1.37564918]
 [ 1.63791059 -1.63058925  0.41684982 ... -0.79883637 -0.22169867
  -0.53762065]
 [ 0.44072866  0.07394008 -0.50691867 ... -1.53917256 -0.71709623
   1.67800276]
 ...
 [-0.54070847  0.61910537 -0.51511711 ...  1.58070836  0.38807746
  -0.01640816]
 [ 0.28882382 -0.18794486 -0.84546408 ... -0.74154275 -0.11421419
   1.14561876]
 [-0.88247241  1.99153557 -1.08427397 ... -0.35012936  1.24025344
   1.98730764]]
mean(X_train_scaled) =  [-1.97530881e-15  2.06057393e-15 -6.75015599e-16 -5.82645043e-16
 -9.02389274e-16 -5.68434189e-15  3.23296945e-15 -1.64845915e-15
  1.71951342e-15]
std(X_train_scaled) =  [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
#Split the data into training and testing. Do not shuffle it!
#Use the first 300 rows for training and the last 200 for testing.
X_test, X_train, y_test, y_train = train_test_split(X_train, y_train, test_size=0.60)
print('dim(X_train) = ', X_train.shape)
print('dim(X_test) = ', X_test.shape)

dim(X_train) =  (300, 9)
dim(X_test) =  (200, 9)


In [6]:
#Using the training dataset build a LinearRegression. 
#What is the intercept and the coefficients associated with the input attributes?
model1 = linear_model.LinearRegression(fit_intercept=True)
model1.fit(X_train,y_train)
print('Intercept =' , model1.intercept_)
print('Coefficents =',model1.coef_)

Intercept = 12.450664920418433
Coefficents = [-1.95752667 -4.23831712 -0.69697596 -0.13098005  0.07689151 -0.85011469
 -2.67311759  0.02621438 -0.00701815]


In [7]:
l2_cv = RidgeCV(alphas = [0.001,.01, 0.1], cv=None, store_cv_values=True)
l2_cv.fit(X_train,y_train)
print('alpha =', l2_cv.alpha_)
print('coef =', l2_cv.coef_)

alpha = 0.1
coef = [ 0.12869337 -0.71911467  0.38336613 -0.13570652  0.06672259 -0.26807035
 -1.8998648   0.02858811 -0.00748371]


In [8]:
#Using the training dataset build 100 L1-regularized linear models corresponding to 100 regularization coefficients evenly spaced between 0.001 and 0.1.
#Use the 10-fold cross validation to find the best regularization coefficient.
#What is the intercept and the coefficients associated with the input attributes corresponding to the best regularization coefficient?
print('dim(cv_values)=', l2_cv.cv_values_.shape)
print('cv_values(all) =\n', l2_cv.cv_values_[:100,:])
print('cv_values(alpha = 0.001) =\n', l2_cv.cv_values_[:100,0])
print('cv_values(alpha = 0.01) =\n', l2_cv.cv_values_[:100,1])
print('cv_values(alpha = 0.1) =\n', l2_cv.cv_values_[:100,2])

dim(cv_values)= (300, 3)
cv_values(all) =
 [[6.42028732e-01 6.49595529e-01 6.26688851e-01]
 [1.67977465e-03 1.61751566e-03 2.00986446e-03]
 [7.21736991e-01 7.34338259e-01 7.53236571e-01]
 [7.31805410e-01 7.35680687e-01 7.33034624e-01]
 [1.94781345e-01 1.91062135e-01 1.95583689e-01]
 [4.39387552e-01 4.34188335e-01 3.78632132e-01]
 [1.28841730e+00 1.29136768e+00 1.27510237e+00]
 [1.44609159e-01 1.44542357e-01 1.35731837e-01]
 [6.98719044e-02 5.57701133e-02 2.80797276e-02]
 [1.20838439e+00 1.19631127e+00 1.18186635e+00]
 [4.65585825e-01 4.68779016e-01 4.62898075e-01]
 [1.37084653e-01 1.52206922e-01 2.08894244e-01]
 [2.07206617e-03 1.85468469e-03 1.82055390e-05]
 [3.09983102e-02 3.26270010e-02 2.97702262e-02]
 [6.40771320e-01 6.34874563e-01 6.16334054e-01]
 [1.28387941e-01 1.28321398e-01 1.26589547e-01]
 [2.24800907e+00 2.26192149e+00 2.32627350e+00]
 [2.27554036e-01 2.01476726e-01 1.41721539e-01]
 [2.05204406e-02 2.06722042e-02 2.64041271e-02]
 [5.31892982e-01 5.52943245e-01 6.62854871e-0

In [9]:
# Get the mean and standard error of the performance metric - by default is the mean squared errors
means_MSE = l2_cv.cv_values_.mean(axis=0)
SEs_MSE = l2_cv.cv_values_.std(axis=0)/np.sqrt(l2_cv.cv_values_.shape[0])
print('means = ', means_MSE)
print('SEs = ', SEs_MSE)

means =  [0.4602001  0.45770368 0.45461766]
SEs =  [0.03469632 0.03457116 0.03425023]


In [10]:
#Provide the 95% confidence interval in the above mean (you will need to compute the Standard Error)
print('95% conf. int. avg. pred. MSE (alpha=0.1) = [', means_MSE[0]-1.96*SEs_MSE[0],
      ', ', means_MSE[0]+1.96*SEs_MSE[0], ']')

y_pred_test = l2_cv.predict(X_test)
test_RMSE = mean_squared_error(y_test, y_pred_test)
print('testing error obtained in testing dataset = ', test_RMSE)

95% conf. int. avg. pred. MSE (alpha=0.1) = [ 0.3921953188918105 ,  0.5282048767162516 ]
testing error obtained in testing dataset =  0.5339582425071275


In [11]:
#Linear Regression - training RMSE
#Linear Regression - testing RMSE
model2 = linear_model.LinearRegression(fit_intercept=True)
model2.fit(X_train,y_train)
training_prediction = model2.predict(X_train)
print('RMSE train = ', math.sqrt(mean_squared_error(training_prediction,y_train)))
testing_prediction = model2.predict(X_test)
print('RMSE test = ', math.sqrt(mean_squared_error(testing_prediction,y_test)))

RMSE train =  0.6573889582153222
RMSE test =  0.7315193443028971


In [12]:
#Lasso (best alpha) - training RMSE
#Lasso (best alpha) - testing RMSE
lasso = LassoCV(alphas = [0.001,.01, 0.1])
lasso.fit(X_train,y_train)
training_prediction = lasso.predict(X_train)
print('RMSE train = ', math.sqrt(mean_squared_error(training_prediction,y_train)))
testing_prediction = lasso.predict(X_test)
print('RMSE test = ', math.sqrt(mean_squared_error(testing_prediction,y_test)))

RMSE train =  0.6591931303254477
RMSE test =  0.7300134597089345


In [13]:
#Lasso (best alpha) - average RMSE obtained by averaging the 10 RMSEs obtained during cross-validation
lasso = LassoCV(alphas = [0.001,.01, 0.1], cv = 10)
lasso.fit(X_train,y_train)
training_prediction = lasso.predict(X_train)
print('Average RMSE train = ', (math.sqrt(mean_squared_error(training_prediction,y_train))))
testing_prediction = lasso.predict(X_test)
print('Average RMSE test = ', math.sqrt(mean_squared_error(testing_prediction,y_test)))

Average RMSE train =  0.6591931303254477
Average RMSE test =  0.7300134597089345


In [ ]:
#Q1. Which model do you prefer between the Linear Regression and Lasso (best alpha) and why?
#Upon conducting both tests, I think Lasso(best alpha regression) would be better as with lasso regression
#it primarily focuses on penalizing the absolute value of reg coefficients. Moreover, though in some cases lasso madels 
#may have an underfitting problem with its data points/features, it can help improve lin reg models accuracy. Lasso model 
#regression utilizes absolte values in each respective penality function. 

In [1]:
#Q2. What additional information Lasso gives about predicting the target?
#Other info that lasso gives with regards to predicting target is that lasso can bring down the coefficient magnitude
#to zero even at the lass(best alpha). With this said, its indicative that lasso models are selective in which coefficients 
#get reduced to 0 which in retrun represents feature selection. Moreover since lasso regression models bud off of 
#L1 regularization models, in some cases you might have models where some predicator coefficeints share strong correlation,
#and with that many predictor coefficients sharing a strong correltion, lasso ensures in selecting one of the predictors 
#and making all others 0

In [2]:
#Q3. What observation can you make by comparing the 95% confidence interval for the mean RMSE and the testing RMSE for Lasso

In [ ]:
#testing RMSE is greater than train RMSE for lasso which represents a good fit in the model. Data is being validated 
#appropriately and it appears theres no overfitting .